# Generated by Django 3.2.23 on 2023-12-10 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
        ('cloths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
