# Generated by Django 3.2.24 on 2024-02-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloths', '0006_alter_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
