# Generated by Django 3.2.25 on 2024-05-22 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloths', '0007_alter_cloth_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='price',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(50000)], verbose_name='price'),
        ),
    ]
